### ISSUE TITLE
What Type of Scanners are Supported

### ISSUE THREAD

**Issue by aaronbach** [Shashank2406/cordova-plugin-zebra-scanner-ios#1]
Hi @Shashank2406 ,

what kind of Scanners do your Plugin is supporting? I am Working on an project where we need to use the `Zebra RFD8500` in Combination with `IONIC 4`. At the moment we are using the `human-interface-mode (HID)`. 

Do your plugin supports the `Zebra RFD8500`. And what basic steps I need to go, to try the plugin myself? Do you have some Kind of `Getting started`?

Thanks for your work

**Comment by Shashank2406** [comment]
Hi @aaronbach ,

The plugin supports all the scanner's that are listed in Zebra iOS SDK support. Yes Zebra RFD8500 is supported. Here is the link for the iOS SDK of Zebra for support info 
https://www.zebra.com/us/en/support-downloads/software/developer-tools/scanner-sdk-for-iOS.html

I have updated the readme with Installation instruction, let me know if you have any issues integrating it.

**Comment by aaronbach** [comment]
Thanks! 
I will try it later this week.

**Comment by Shashank2406** [comment]
No problem
