### ISSUE TITLE
undefined is not an object ZebraScanner.getAvailableScanners

### ISSUE THREAD

**Issue by gatewayparth** [Shashank2406/cordova-plugin-zebra-scanner-ios#4]
Hello 

We are use your plugin in our project which is made ionic 3 and we are getting error "undefined is not an object (evaluating 'window['cordova'].ZebraScanner.getAvailableScanners')" in iOS platform. We are also try with window.ZebraScanner.getAvailableScanners . but we getting same error.  Can you please suggest any solution?

**Comment by Shashank2406** [comment]
Hello
Can you please tell me all the steps that you followed so that we can replicate this issue, also can you try if you can access window.ZebraScanner ??
